apiVersion: v1
kind: Secret
metadata:
  name: model-artifacts-minio
  namespace: llm-serving
type: Opaque
stringData:
  endpoint: http://host.minikube.internal:9000
  access_key: minio
  secret_key: minioadmin
